name: recipes_app
description: Каталог блюд и рецептов
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
